name: flutter_common
description: Flutter Common package.
version: 0.5.4
homepage: https://github.com/wiatec
repository: https://github.com/wiatec/flutter_common

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  dio: ^3.0.7
  encrypt: ^3.3.1
  crypto: ^2.1.3
  screen: ^0.0.5
  provide: ^1.0.2
  path: ^1.6.4
  share: ^0.6.3+4
  path_provider: ^1.4.5
  device_info: ^0.4.1+3
  package_info: ^0.4.0+12
  connectivity: ^0.4.5+7
  json_annotation: ^3.0.0
  shared_preferences: ^0.5.4+8
  url_launcher: ^5.2.7
  rxdart: ^0.22.6
  local_auth: ^0.6.1
  logger: ^0.7.0+2
  sqflite: ^1.1.7+3

  # widgets
  cached_network_image: ^2.0.0-rc
  flutter_slidable: ^0.5.4
  webview_flutter: ^0.3.17
  fluttertoast: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true


# sudo flutter packages pub publish --dry-run
# sudo flutter packages pub publish